---
kind: pipeline
type: docker
name: test-drone

steps:
- name: build
  image: gcc
  commands:
  - gcc -o test-drone test-drone.c

- name: test
  image: ubuntu
  commands:
  - echo start
  - echo testing